twag:
  name: vectorcore-twag-1
  realm: epc.mnc001.mcc001.3gppnetwork.org

logging:
  level: info
  file: /tmp/vectorcore-twag/twag.log

access:
  mode: ethernet
  interface: eth1

aaa:
  mode: swx
  swx:
    origin_host: twag01.epc.mnc001.mcc001.3gppnetwork.org
    origin_realm: epc.mnc001.mcc001.3gppnetwork.org
    destination_realm: ims.mnc001.mcc001.3gppnetwork.org
    destination_host: hss01.ims.mnc001.mcc001.3gppnetwork.org
    peer_addr: 192.168.10.5:3868

subscriber:
  default_apn: internet
  default_realm: ims.mnc001.mcc001.3gppnetwork.org

ipam:
  pool: 10.200.0.0/24
  gateway: 10.200.0.1
  dns:
    - 8.8.8.8
    - 1.1.1.1

pgw:
  mode: stub
  local_gtpc_ip: 192.168.10.20
  local_gtpu_ip: 192.168.10.20
  remote_pgw_gtpc_ip: 192.168.10.10
  remote_pgw_gtpu_ip: 192.168.10.10
  apn: internet

routing:
  enable_ip_forwarding: true
  install_routes: true
  nat_enabled: false
  nat_interface: eth0
